language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm   # ZIP Error(11): Status(0): Arhive(cache/zipTest.zip): Directory(cache)
before_script:
  - composer self-update
  - composer install --no-interaction
  - \[ -f "config_si.php" \] || cp tests/travis_config_si.php config_si.php
  - php tests/testinstall.php
script:
  - cd tests
  - ../vendor/bin/phpunit
  - cat ../suitecrm.log
services:
  - mysql
branches:
  only:
    - master
    - hotfix
    - develop
    - suitep
